/**
 * lib/content.ts
 * ───────────────
 * Single source of truth for all user-facing copy in English and Spanish.
 * Components accept `lang?: 'en' | 'es'` and pull from here.
 * To add a new language: add a new key matching the Locale type.
 */

export type Locale = "en" | "es";

export const content = {
  en: {
    nav: {
      phone: "(555) 000-1234",
      cta: "Get My Cash Offer",
      links: [
        { label: "How It Works", href: "#how-it-works" },
        { label: "Why Us", href: "#comparison" },
        { label: "Reviews", href: "#testimonials" },
        { label: "FAQ", href: "#faq" },
      ],
    },
    hero: {
      eyebrow: "White-Glove Cash Offer Experience",
      lines: ["Your Home.", "Your Terms.", "Your Cash."],
      sub: "Skip the repairs, the showings, and the uncertainty. We make fair, all-cash offers in as little as 24 hours — and close on your schedule, not ours.",
      cta: "Get My Cash Offer",
      secondaryCta: "See How It Works",
      addressPlaceholder: "Enter your property address",
      stats: [
        { value: "500+", label: "Homes Purchased" },
        { value: "24 hrs", label: "Offer Turnaround" },
        { value: "$0", label: "Commissions or Fees" },
        { value: "7 days", label: "Minimum Closing" },
      ],
    },
    trustBar: {
      sectionLabel: "The Standard We Hold Ourselves To",
      items: [
        { label: "No Repairs Required", sub: "Sell as-is, any condition" },
        { label: "Offer in 24 Hours", sub: "Fast, certain, stress-free" },
        { label: "Zero Agent Commissions", sub: "You keep every dollar" },
        { label: "No Hidden Fees", sub: "The offer is what you get" },
        { label: "Close on Your Schedule", sub: "7 days to 6 months — your call" },
        { label: "Local & Trusted", sub: "Serving your community" },
      ],
      ratingText: "4.9 / 5 across 200+ reviews",
      badge1: "Licensed & Insured Buyer",
      badge2: "No-Obligation Offer Guarantee",
    },
    howItWorks: {
      eyebrow: "The Process",
      headline: "Three steps to a stress-free sale",
      sub: "We've stripped out every unnecessary step so selling your home feels simple again.",
      steps: [
        {
          title: "Tell Us About Your Property",
          description: "Fill out our simple 2-minute form — just the basics. Property address, your contact info, and a few details about your situation. No inspection, no photos needed.",
          time: "2 minutes",
        },
        {
          title: "We Review & Reach Out",
          description: "Our team personally reviews your property details and reaches out within 24 hours. We may ask a few light follow-up questions — nothing invasive, no pressure.",
          time: "Within 24 hours",
        },
        {
          title: "Receive Your Cash Offer",
          description: "We present a clear, fair, all-cash offer — no lowballs, no games. Take your time to review it. If it works for you, we move forward. No obligation if it doesn't.",
          time: "No obligation",
        },
      ],
      cta: "Start With Your Address",
    },
    pain: {
      eyebrow: "We Understand Your Situation",
      headline: "Life doesn't wait for the",
      headlineItalic: "perfect market",
      sub: "Whether you're navigating a difficult chapter or simply need to move on quickly, we meet you where you are — without judgment, without pressure.",
      situations: [
        { label: "Foreclosure Risk", description: "Behind on mortgage payments and running out of runway? A cash sale can close before the bank does — protecting your credit and your dignity." },
        { label: "Inherited Property", description: "Inherited a home you don't need — or can't afford to maintain? We handle properties in any condition, in any estate situation." },
        { label: "Going Through Divorce", description: "When life changes, the house often needs to change too. We move quickly and discreetly so both parties can move forward." },
        { label: "Tired Landlord", description: "Done managing tenants, repairs, and late rent? We buy tenant-occupied properties. No need to wait for them to leave." },
        { label: "Major Repairs Needed", description: "Foundation issues. Old roof. Outdated systems. We buy homes as-is — you won't spend a dollar on repairs before closing." },
        { label: "Relocating Quickly", description: "New job, new city, new chapter. When timing matters, a certain cash sale beats months of uncertainty on the open market." },
        { label: "Downsizing", description: "Ready for a simpler life with less to manage? We make the transition seamless — fast close, no hassle, your timeline." },
        { label: "Problem Property", description: "Fire damage, code violations, squatters, or a title issue? We've seen it all. We handle the complexity so you don't have to." },
      ],
      cta: "Tell Us About Your Property",
    },
    comparison: {
      eyebrow: "The Honest Comparison",
      headline: "The difference is clear",
      sub: "Traditional listing has its place — but when speed, certainty, and simplicity matter, the numbers don't lie.",
      ourLabel: "BuyYourCasa",
      theirLabel: "Traditional Listing",
      rows: [
        { label: "Closing timeline", us: "7–30 days (your choice)", them: "30–90+ days (not guaranteed)" },
        { label: "Repairs required", us: "None — sell completely as-is", them: "Often $10,000–$50,000+ in prep" },
        { label: "Agent commission", us: "Zero", them: "5–6% of sale price" },
        { label: "Hidden fees & costs", us: "None, ever", them: "Closing costs, staging, inspection fees" },
        { label: "Open houses & showings", us: "No showings required", them: "Weeks of disruption to your life" },
        { label: "Financing fall-through risk", us: "Zero — all-cash buyer", them: "Significant risk even after acceptance" },
        { label: "Price uncertainty", us: "Firm offer, no renegotiation", them: "Buyers often renegotiate after inspection" },
        { label: "Privacy", us: "Completely private transaction", them: "Public MLS listing, open-market exposure" },
      ],
      cta: "Get My Free Offer — No Obligation",
    },
    testimonials: {
      eyebrow: "Seller Stories",
      headline: "Real people.",
      headlineItalic: "Real relief.",
      sub: "Every home we purchase comes with a story. These are a few of them.",
      items: [
        { quote: "I inherited my mother's house and had no idea what to do. The team walked me through everything, never pressured me, and closed in 11 days. I cried with relief. The whole experience felt dignified.", name: "Margaret T.", situation: "Inherited Property — Atlanta, GA", initials: "MT", rating: 5 },
        { quote: "We were three months behind on mortgage and I thought we were going to lose everything. BuyYourCasa gave us a fair offer the same week I called, and we closed before the bank could act. Life-changing.", name: "Darnell & Keisha W.", situation: "Foreclosure Prevention — Birmingham, AL", initials: "DW", rating: 5 },
        { quote: "My ex and I needed out fast. The property was in rough shape and neither of us wanted to deal with showings or a realtor. These guys bought it as-is. Smooth, professional, and genuinely kind throughout.", name: "Sandra R.", situation: "Divorce Settlement — Nashville, TN", initials: "SR", rating: 5 },
        { quote: "After 14 years as a landlord I was burned out. Nightmare tenants, deferred maintenance — I just wanted out. Got a solid offer in 24 hours, tenants in place. Nothing I could have gotten on the open market this cleanly.", name: "Robert H.", situation: "Tired Landlord — Charlotte, NC", initials: "RH", rating: 5 },
        { quote: "The roof was caved in on one side. Every realtor told me to put $40K into it first. BuyYourCasa made an offer without blinking. Fair price, zero repairs. I'd recommend them to anyone in a tough spot.", name: "Linda V.", situation: "Major Repairs — Memphis, TN", initials: "LV", rating: 5 },
      ],
      rating: "4.9",
      reviewCount: "200+",
      recommendPct: "98%",
      labels: { rating: "Average Rating", reviews: "Verified Reviews", recommend: "Would Recommend" },
    },
    serviceArea: {
      eyebrow: "Service Area",
      headline: "Serving homeowners",
      headlineItalic: "across the Southeast",
      sub: "We buy houses in major metros and surrounding communities throughout the Southeast. Whether you're in the heart of a city or outside the suburbs, we can make you an offer.",
      notSureLabel: "Not sure if we cover your area?",
      notSureSub: "Submit your address and we'll let you know within minutes. We're always expanding.",
      cta: "Check My Area",
    },
    faq: {
      eyebrow: "Common Questions",
      headline: "Every question,",
      headlineItalic: "answered honestly",
      sub: "Transparency is non-negotiable for us. If you don't see your question here, reach out — we'll give you a straight answer.",
      stillHave: "Still have questions?",
      items: [
        { q: "Are there any fees or commissions?", a: "None, ever. We are the buyer — not a middleman or an agent. There are no commissions, no closing cost surprises, no hidden fees of any kind. The offer we present is the number that hits your account." },
        { q: "Do I need to repair or clean the property?", a: "Absolutely not. We buy homes in any condition — whether that means a leaky roof, fire damage, full of belongings, or decades of deferred maintenance. Leave what you want, take what you want. We handle the rest." },
        { q: "How quickly can we close?", a: "In many cases, we can close in as little as 7 business days once you accept our offer. If you need more time — weeks or even months — that's completely fine too. We work on your schedule, not ours." },
        { q: "Is there any obligation to accept the offer?", a: "Zero. We make a fair, no-pressure offer and you decide. There's no contract until you're ready to sign, no one will call you repeatedly, and you can walk away at any point with no consequences." },
        { q: "What types of properties do you purchase?", a: "We buy single-family homes, condos, townhomes, multi-family properties, vacant land, inherited properties, and more. Occupied or vacant — both work fine." },
        { q: "How is my offer amount determined?", a: "We analyze recent comparable sales in your area, the property's current condition, the local market trajectory, and our estimated carrying and renovation costs. We aim for fair, not predatory — and we always explain our reasoning." },
        { q: "What if the home has title issues or liens?", a: "We've worked through title issues, tax liens, probate complications, and more. These situations are often what prevent a traditional sale — but we have the experience and legal resources to navigate them." },
        { q: "How is this different from iBuyers like Opendoor?", a: "Unlike algorithm-driven iBuyers, we're local, human, and personally invested in every transaction. We don't charge service fees, we don't have rigid qualification criteria, and we can move faster on complex or non-standard properties that iBuyers routinely decline." },
      ],
    },
    form: {
      eyebrow: "Get Started",
      headline: "Two minutes.",
      headlineItalic: "A fair offer.",
      headlineSuffix: "No strings attached.",
      sub: "Tell us about your property and we'll have a fair, no-obligation cash offer back to you within 24 hours. It really is that simple.",
      reassurances: [
        "No obligation — you decide if it works for you",
        "We never share or sell your information",
        "No inspection or photos needed to get started",
        "Our team personally reviews every submission",
      ],
      steps: [
        { title: "Where is the property?", sub: "Enter the full address and we'll begin pulling local data right away.", label: "Property Address", placeholder: "123 Maple Street, Atlanta, GA 30301" },
        { title: "How do we reach you?", sub: "We'll use this only to deliver your cash offer — nothing else.", labels: { firstName: "First Name", lastName: "Last Name", phone: "Phone Number", email: "Email Address" }, placeholders: { firstName: "First name", lastName: "Last name", phone: "(555) 000-0000", email: "you@example.com" } },
        { title: "Tell us a bit more", sub: "These details help us tailor a more accurate offer for your situation." },
        { title: "Review & Submit", sub: "Everything look right? We'll have your offer ready within 24 hours." },
      ],
      conditionLabel: "Property Condition",
      timelineLabel: "Ideal Closing Timeline",
      reasonLabel: "Reason for Selling",
      reasonOptional: "(optional)",
      conditions: [
        { value: "excellent", label: "Great Shape", sub: "Move-in ready, minimal work needed" },
        { value: "good", label: "Good Condition", sub: "Minor cosmetic updates" },
        { value: "fair", label: "Fair Condition", sub: "Some repairs needed" },
        { value: "poor", label: "Needs Work", sub: "Significant repairs or damage" },
      ],
      timelines: [
        { value: "asap", label: "ASAP", sub: "7–14 days if possible" },
        { value: "1_month", label: "Within 30 Days", sub: "Flexible but soon" },
        { value: "3_months", label: "1–3 Months", sub: "Planning ahead" },
        { value: "flexible", label: "Flexible", sub: "No hard deadline" },
      ],
      reasons: ["Inherited Property", "Foreclosure / Behind on Payments", "Divorce", "Relocating", "Tired Landlord", "Major Repairs Needed", "Downsizing", "Estate Sale", "Financial Hardship", "Other / Prefer Not to Say"],
      reasonDefault: "Select a reason...",
      cta: "Continue",
      submitCta: "Submit & Get My Offer",
      microcopy: "No obligation · No spam · 100% free",
      successTitle: "You're all set,",
      successSub: "We've received your submission and a member of our team will be in touch within 24 hours with your cash offer. No pressure, no obligation.",
      successMicro: ["No obligation", "No pressure", "Just a fair offer"],
      privacyNote: "By submitting, you agree to be contacted by our team. We respect your privacy — no spam, no sharing your info with third parties, ever.",
      editLabel: "Edit",
      backLabel: "Back",
      summaryLabels: { property: "Property", contact: "Contact", details: "Details" },
    },
    finalCta: {
      headline: "The offer is waiting.",
      headlineItalic: "The next step is yours.",
      sub: "No obligation. No rush. Just a fair cash offer from a team that genuinely respects your time, your situation, and your home.",
      cta: "Get My Free Cash Offer",
      micros: ["No obligation", "No repairs needed", "No agent fees", "Close in 7 days"],
    },
    // Mobile-specific
    mobileHero: {
      eyebrow: "Cash Offer · 24 Hours",
      headline: "Sell Fast.",
      headlineItalic: "Get Cash.",
      sub: "No repairs. No agents. No hidden fees.",
      addressPlaceholder: "Enter your property address",
      cta: "Get My Cash Offer",
      microcopy: "No obligation · Free · Takes 2 minutes",
      stats: [
        { value: "500+", label: "Homes Bought" },
        { value: "24hr", label: "Offer Time" },
        { value: "$0", label: "Fees Ever" },
      ],
    },
    mobilePain: {
      eyebrow: "We Understand",
      headline: "Sound familiar?",
      sub: "We've helped homeowners in every one of these situations.",
      chips: ["Facing foreclosure?", "Inherited a house?", "Going through divorce?", "Tired of tenants?", "Needs major repairs?", "Relocating fast?", "Behind on payments?", "Downsizing?", "Estate sale?", "Problem property?"],
      empathy: "Whatever your situation — we meet you where you are,",
      empathyStrong: "without judgment or pressure.",
      cta: "Get a No-Pressure Offer",
    },
    mobileForm: {
      eyebrow: "Get Started",
      headline: "Your offer is",
      headlineItalic: "2 minutes away",
      steps: [
        { title: "Where is the property?", sub: "Just the address to get started.", label: "Property Address", placeholder: "123 Maple Street, Atlanta, GA" },
        { title: "What's your phone number?", sub: "We'll call or text you with your offer.", label: "Phone Number", placeholder: "(555) 000-0000", privacyNote: "We never sell or share your number." },
        { title: "What's your name?", sub: "So we know who to address your offer to.", labels: { first: "First Name", last: "Last Name", email: "Email (optional)" }, placeholders: { first: "First name", last: "Last name", email: "you@example.com" } },
        { title: "Tell us about the property", sub: "Two quick questions — no wrong answers." },
        { title: "Looks good,", sub: "Review and submit — we'll have your offer within 24 hours." },
      ],
      stepLabels: ["Address", "Phone", "Name", "Details", "Confirm"],
      conditions: [
        { value: "excellent", emoji: "✨", label: "Great Shape", sub: "Move-in ready" },
        { value: "good", emoji: "👍", label: "Good", sub: "Minor cosmetic work" },
        { value: "fair", emoji: "🔨", label: "Needs Work", sub: "Some repairs" },
        { value: "poor", emoji: "🏚", label: "Major Work", sub: "Significant damage" },
      ],
      timelines: [
        { value: "asap", label: "ASAP", sub: "7–14 days" },
        { value: "30days", label: "30 Days", sub: "Somewhat urgent" },
        { value: "90days", label: "1–3 Months", sub: "Planning ahead" },
        { value: "flexible", label: "Flexible", sub: "No deadline" },
      ],
      reasons: ["Foreclosure / Behind on Payments", "Inherited Property", "Divorce", "Relocating", "Tired Landlord", "Major Repairs", "Downsizing", "Estate Sale", "Other / Prefer Not to Say"],
      reasonDefault: "Select if you'd like...",
      conditionLabel: "Property Condition",
      timelineLabel: "Ideal Closing Timeline",
      reasonLabel: "Reason for Selling",
      reasonOptional: "(optional)",
      cta: "Continue",
      submitCta: "Get My Cash Offer",
      microcopy: "No obligation · No spam · Free",
      stepsLeft: (n: number) => `${n} step${n > 1 ? "s" : ""} left`,
      readyLabel: "Ready to submit",
      successTitle: "You're all set,",
      successSub: "Our team will reach out within 24 hours with your cash offer. No pressure, no obligation.",
      callLabel: "Rather talk now? Call us.",
      privacyNote: "By submitting, you agree to be contacted about your property. We respect your privacy — no spam, no third-party sharing.",
      editLabel: "Edit",
      backLabel: "← Back",
      summaryLabels: { property: "Property", phone: "Phone", name: "Name", condition: "Condition" },
    },
    // Voice Agent UI (English)
    voice: {
      idleTitle: "Get your cash offer in 2 minutes.",
      idleSub: "Tap to start a quick conversation — no forms, no typing. I'll ask a few questions and our team will call you back with a fair, no-obligation offer.",
      startButton: "Tap to Talk",
      startingLabel: "Connecting…",
      connectingLabel: "Connecting…",
      listeningLabel: "Listening",
      speakingLabel: "Speaking",
      thinkingLabel: "Thinking…",
      endCallLabel: "End call",
      muteLabel: "Mute",
      unmuteLabel: "Unmute",
      fallbackLink: "Prefer to type? Fill a quick form instead",
      typeHint: "Prefer to type instead? You can answer here too.",
      typeQueuedHint: "Type your answer here. I'll send it as soon as the call connects.",
      typePlaceholder: "Type your answer here",
      typeSend: "Send",
      learnMoreLink: "Learn more about us ↓",
      micBlockedTitle: "Microphone blocked",
      micBlockedSub: "I need your mic so we can chat — it is much faster than typing. Click the lock icon in your browser address bar, set Microphone to Allow, then refresh this page.",
      micBlockedRetry: "I have allowed it — try again",
      micBlockedFallback: "Can't use mic right now? Fill a form instead",
      errorTitle: "Something went wrong",
      errorSub: "The call didn't connect. Let's try that again, or you can fill a quick form instead.",
      errorRetry: "Try again",
      successTitle: "Thanks,",
      successSub: "We have what we need. Our team will call you within 24 hours with your cash offer — no obligation.",
      successMicro: ["No obligation", "No pressure", "Just a fair offer"],
      summaryTitle: "Here is what we captured",
      summaryEmpty: "Not provided",
      summaryLabels: {
        address: "Property address",
        name: "Name",
        phone: "Phone",
        email: "Email",
        condition: "Condition",
        timeline: "Timeline",
        reason: "Reason for selling",
      },
      summaryValues: {
        condition: {
          excellent: "Great shape",
          good: "Good condition",
          fair: "Some repairs needed",
          needs_work: "Needs work",
        },
        timeline: {
          asap: "As soon as possible",
          "1_3_months": "1-3 months",
          "3_6_months": "3-6 months",
          exploring: "Just exploring",
        },
      },
      trustRow: ["SSL Secured", "No Spam Policy", "Data Protected"],
    },

  },

  // ─── SPANISH ──────────────────────────────────────────────────────────────
  es: {
    nav: {
      phone: "(555) 000-1234",
      cta: "Obtener Mi Oferta",
      links: [
        { label: "Cómo Funciona", href: "#how-it-works" },
        { label: "Por Qué Nosotros", href: "#comparison" },
        { label: "Testimonios", href: "#testimonials" },
        { label: "Preguntas", href: "#faq" },
      ],
    },
    hero: {
      eyebrow: "Experiencia Premium de Oferta en Efectivo",
      lines: ["Tu Casa.", "Tus Términos.", "Tu Efectivo."],
      sub: "Olvídate de las reparaciones, las visitas y la incertidumbre. Hacemos ofertas justas en efectivo en tan solo 24 horas — y cerramos en tu horario, no en el nuestro.",
      cta: "Obtener Mi Oferta en Efectivo",
      secondaryCta: "Ver Cómo Funciona",
      addressPlaceholder: "Ingresa la dirección de tu propiedad",
      stats: [
        { value: "500+", label: "Casas Compradas" },
        { value: "24 hrs", label: "Tiempo de Oferta" },
        { value: "$0", label: "Comisiones o Cargos" },
        { value: "7 días", label: "Cierre Mínimo" },
      ],
    },
    trustBar: {
      sectionLabel: "Nuestro Estándar de Calidad",
      items: [
        { label: "Sin Reparaciones", sub: "Vende como está, en cualquier condición" },
        { label: "Oferta en 24 Horas", sub: "Rápida, segura y sin estrés" },
        { label: "Sin Comisiones", sub: "Tú te quedas con todo el dinero" },
        { label: "Sin Cargos Ocultos", sub: "La oferta es lo que recibes" },
        { label: "Cierra Cuando Quieras", sub: "7 días a 6 meses — tú decides" },
        { label: "Local y de Confianza", sub: "Sirviendo a tu comunidad" },
      ],
      ratingText: "4.9 / 5 con más de 200 reseñas",
      badge1: "Comprador Licenciado y Asegurado",
      badge2: "Oferta Sin Compromiso Garantizada",
    },
    howItWorks: {
      eyebrow: "El Proceso",
      headline: "Tres pasos para una venta sin estrés",
      sub: "Eliminamos cada paso innecesario para que vender tu casa vuelva a ser simple.",
      steps: [
        {
          title: "Cuéntanos Sobre Tu Propiedad",
          description: "Completa nuestro formulario simple de 2 minutos — solo lo básico. Dirección, información de contacto y algunos detalles sobre tu situación. No se necesita inspección ni fotos.",
          time: "2 minutos",
        },
        {
          title: "Revisamos y Te Contactamos",
          description: "Nuestro equipo revisa personalmente los detalles de tu propiedad y te contacta dentro de las 24 horas. Podemos hacerte algunas preguntas de seguimiento — nada invasivo, sin presión.",
          time: "Dentro de 24 horas",
        },
        {
          title: "Recibe Tu Oferta en Efectivo",
          description: "Presentamos una oferta clara, justa y en efectivo — sin ofertas bajas ni juegos. Tómate tu tiempo para revisarla. Si te conviene, avanzamos. Sin obligación si no es así.",
          time: "Sin obligación",
        },
      ],
      cta: "Empieza con Tu Dirección",
    },
    pain: {
      eyebrow: "Entendemos Tu Situación",
      headline: "La vida no espera al",
      headlineItalic: "mercado perfecto",
      sub: "Ya sea que estés atravesando un momento difícil o simplemente necesites seguir adelante rápidamente, te encontramos donde estás — sin juicios, sin presión.",
      situations: [
        { label: "Riesgo de Ejecución Hipotecaria", description: "¿Atrasado en los pagos de la hipoteca y sin margen de maniobra? Una venta en efectivo puede cerrar antes que el banco actúe, protegiendo tu crédito y tu dignidad." },
        { label: "Propiedad Heredada", description: "¿Heredaste una casa que no necesitas o no puedes mantener? Compramos propiedades en cualquier condición y en cualquier situación de herencia." },
        { label: "Proceso de Divorcio", description: "Cuando la vida cambia, la casa a menudo también necesita cambiar. Actuamos con rapidez y discreción para que ambas partes puedan seguir adelante." },
        { label: "Propietario Agotado", description: "¿Cansado de manejar inquilinos, reparaciones y rentas tardías? Compramos propiedades con inquilinos. No necesitas esperar a que se vayan." },
        { label: "Reparaciones Mayores Necesarias", description: "Problemas de cimientos. Techo viejo. Sistemas obsoletos. Compramos casas como están — no gastarás un centavo en reparaciones antes de cerrar." },
        { label: "Mudanza Urgente", description: "Nuevo trabajo, nueva ciudad, nuevo capítulo. Cuando el tiempo importa, una venta segura en efectivo supera meses de incertidumbre en el mercado abierto." },
        { label: "Reducción de Espacio", description: "¿Listo para una vida más simple con menos que administrar? Hacemos la transición sin problemas — cierre rápido, sin complicaciones, a tu ritmo." },
        { label: "Propiedad Problemática", description: "¿Daños por incendio, violaciones de código, ocupantes ilegales o problemas de título? Lo hemos visto todo. Manejamos la complejidad para que tú no tengas que hacerlo." },
      ],
      cta: "Cuéntanos Sobre Tu Propiedad",
    },
    comparison: {
      eyebrow: "La Comparación Honesta",
      headline: "La diferencia es clara",
      sub: "La venta tradicional tiene su lugar — pero cuando la velocidad, la certeza y la simplicidad importan, los números no mienten.",
      ourLabel: "BuyYourCasa",
      theirLabel: "Venta Tradicional",
      rows: [
        { label: "Tiempo de cierre", us: "7–30 días (tu elección)", them: "30–90+ días (sin garantía)" },
        { label: "Reparaciones requeridas", us: "Ninguna — vende completamente como está", them: "A menudo $10,000–$50,000+ en preparación" },
        { label: "Comisión de agente", us: "Cero", them: "5–6% del precio de venta" },
        { label: "Cargos y costos ocultos", us: "Ninguno, nunca", them: "Costos de cierre, staging, inspección" },
        { label: "Casas abiertas y visitas", us: "Sin visitas requeridas", them: "Semanas de interrupciones en tu vida" },
        { label: "Riesgo de financiamiento fallido", us: "Cero — comprador con efectivo", them: "Riesgo significativo incluso tras la aceptación" },
        { label: "Incertidumbre de precio", us: "Oferta firme, sin renegociación", them: "Los compradores suelen renegociar tras la inspección" },
        { label: "Privacidad", us: "Transacción completamente privada", them: "Listado público en MLS, exposición al mercado" },
      ],
      cta: "Obtener Mi Oferta Gratis — Sin Compromiso",
    },
    testimonials: {
      eyebrow: "Historias de Vendedores",
      headline: "Personas reales.",
      headlineItalic: "Alivio real.",
      sub: "Cada casa que compramos viene con una historia. Aquí hay algunas de ellas.",
      items: [
        { quote: "Heredé la casa de mi madre y no sabía qué hacer. El equipo me guió en todo, nunca me presionó, y cerramos en 11 días. Lloré de alivio. Toda la experiencia se sintió digna.", name: "Margaret T.", situation: "Propiedad Heredada — Atlanta, GA", initials: "MT", rating: 5 },
        { quote: "Estábamos tres meses atrasados en la hipoteca y pensé que íbamos a perderlo todo. BuyYourCasa nos dio una oferta justa la misma semana que llamé, y cerramos antes que el banco actuara. Un cambio de vida.", name: "Darnell & Keisha W.", situation: "Prevención de Ejecución — Birmingham, AL", initials: "DW", rating: 5 },
        { quote: "Mi ex y yo necesitábamos salir rápido. La propiedad estaba en mal estado y ninguno quería lidiar con visitas o un agente. Ellos la compraron como estaba. Fluido, profesional y genuinamente amables.", name: "Sandra R.", situation: "Divorcio — Nashville, TN", initials: "SR", rating: 5 },
        { quote: "Después de 14 años como arrendador estaba agotado. Inquilinos problemáticos, mantenimiento postergado — solo quería salir. Tuve una oferta sólida en 24 horas, con inquilinos dentro. No podría haberlo logrado en el mercado abierto tan limpiamente.", name: "Robert H.", situation: "Propietario Agotado — Charlotte, NC", initials: "RH", rating: 5 },
        { quote: "El techo estaba hundido de un lado. Cada agente me dijo que invirtiera $40K primero. BuyYourCasa hizo una oferta sin dudar. Precio justo, cero reparaciones. Los recomendaría a cualquiera en una situación difícil.", name: "Linda V.", situation: "Reparaciones Mayores — Memphis, TN", initials: "LV", rating: 5 },
      ],
      rating: "4.9",
      reviewCount: "200+",
      recommendPct: "98%",
      labels: { rating: "Calificación Promedio", reviews: "Reseñas Verificadas", recommend: "Recomendarían" },
    },
    serviceArea: {
      eyebrow: "Área de Servicio",
      headline: "Sirviendo a propietarios",
      headlineItalic: "en todo el Sureste",
      sub: "Compramos casas en las principales ciudades y comunidades del Sureste. Ya sea en el centro de una ciudad o en los suburbios, podemos hacerte una oferta.",
      notSureLabel: "¿No estás seguro si cubrimos tu área?",
      notSureSub: "Envía tu dirección y te informaremos en minutos. Siempre estamos expandiéndonos.",
      cta: "Verificar Mi Área",
    },
    faq: {
      eyebrow: "Preguntas Frecuentes",
      headline: "Cada pregunta,",
      headlineItalic: "respondida con honestidad",
      sub: "La transparencia es innegociable para nosotros. Si no ves tu pregunta aquí, comunícate con nosotros — te daremos una respuesta directa.",
      stillHave: "¿Aún tienes preguntas?",
      items: [
        { q: "¿Hay alguna tarifa o comisión?", a: "Nunca. Somos el comprador — no un intermediario ni un agente. No hay comisiones, ni sorpresas en los costos de cierre, ni tarifas ocultas de ningún tipo. La oferta que presentamos es el número que llega a tu cuenta." },
        { q: "¿Necesito reparar o limpiar la propiedad?", a: "Absolutamente no. Compramos casas en cualquier condición — ya sea un techo con goteras, daños por incendio, llena de pertenencias o con décadas de mantenimiento postergado. Deja lo que quieras, lleva lo que quieras. Nosotros nos encargamos del resto." },
        { q: "¿Qué tan rápido podemos cerrar?", a: "En muchos casos, podemos cerrar en tan solo 7 días hábiles una vez que aceptas nuestra oferta. Si necesitas más tiempo — semanas o incluso meses — está bien también. Trabajamos según tu horario, no el nuestro." },
        { q: "¿Estoy obligado a aceptar la oferta?", a: "Cero obligación. Hacemos una oferta justa y sin presión, y tú decides. No hay contrato hasta que estés listo para firmar, nadie te llamará repetidamente, y puedes retirarte en cualquier momento sin consecuencias." },
        { q: "¿Qué tipos de propiedades compran?", a: "Compramos casas unifamiliares, condominios, adosados, propiedades multifamiliares, terrenos vacíos, propiedades heredadas y más. Ocupadas o vacantes — ambas funcionan perfectamente." },
        { q: "¿Cómo se determina el monto de mi oferta?", a: "Analizamos ventas comparables recientes en tu área, la condición actual de la propiedad, la trayectoria del mercado local y nuestros costos estimados de mantenimiento y renovación. Apuntamos a ser justos, no depredadores — y siempre explicamos nuestro razonamiento." },
        { q: "¿Qué pasa si la casa tiene problemas de título o gravámenes?", a: "Hemos trabajado con problemas de título, gravámenes fiscales, complicaciones de sucesión y más. Estas situaciones son a menudo las que impiden una venta tradicional — pero tenemos la experiencia y los recursos legales para navegarlas." },
        { q: "¿En qué se diferencia esto de los iBuyers como Opendoor?", a: "A diferencia de los iBuyers impulsados por algoritmos, somos locales, humanos e invertidos personalmente en cada transacción. No cobramos tarifas de servicio, no tenemos criterios de calificación rígidos, y podemos actuar más rápido en propiedades complejas o no estándar que los iBuyers rechazan rutinariamente." },
      ],
    },
    form: {
      eyebrow: "Comenzar",
      headline: "Dos minutos.",
      headlineItalic: "Una oferta justa.",
      headlineSuffix: "Sin compromisos.",
      sub: "Cuéntanos sobre tu propiedad y tendremos una oferta justa en efectivo, sin obligación, de regreso contigo dentro de las 24 horas. Así de simple.",
      reassurances: [
        "Sin obligación — tú decides si te conviene",
        "Nunca compartimos ni vendemos tu información",
        "No se necesita inspección ni fotos para comenzar",
        "Nuestro equipo revisa personalmente cada solicitud",
      ],
      steps: [
        { title: "¿Dónde está la propiedad?", sub: "Ingresa la dirección completa y comenzaremos a recopilar datos locales de inmediato.", label: "Dirección de la Propiedad", placeholder: "123 Calle Maple, Atlanta, GA 30301" },
        { title: "¿Cómo te contactamos?", sub: "Solo lo usaremos para entregarte tu oferta en efectivo — nada más.", labels: { firstName: "Nombre", lastName: "Apellido", phone: "Número de Teléfono", email: "Correo Electrónico" }, placeholders: { firstName: "Nombre", lastName: "Apellido", phone: "(555) 000-0000", email: "tu@ejemplo.com" } },
        { title: "Cuéntanos un poco más", sub: "Estos detalles nos ayudan a preparar una oferta más precisa para tu situación." },
        { title: "Revisar y Enviar", sub: "¿Todo correcto? Tendremos tu oferta lista dentro de las 24 horas." },
      ],
      conditionLabel: "Condición de la Propiedad",
      timelineLabel: "Tiempo Ideal para Cerrar",
      reasonLabel: "Motivo de Venta",
      reasonOptional: "(opcional)",
      conditions: [
        { value: "excellent", label: "Excelente Estado", sub: "Lista para habitar, trabajo mínimo" },
        { value: "good", label: "Buen Estado", sub: "Actualizaciones cosméticas menores" },
        { value: "fair", label: "Estado Regular", sub: "Se necesitan algunas reparaciones" },
        { value: "poor", label: "Necesita Trabajo", sub: "Reparaciones significativas o daños" },
      ],
      timelines: [
        { value: "asap", label: "Lo Antes Posible", sub: "7–14 días si es posible" },
        { value: "1_month", label: "Dentro de 30 Días", sub: "Flexible pero pronto" },
        { value: "3_months", label: "1–3 Meses", sub: "Planificando con anticipación" },
        { value: "flexible", label: "Flexible", sub: "Sin fecha límite" },
      ],
      reasons: ["Propiedad Heredada", "Ejecución Hipotecaria / Pagos Atrasados", "Divorcio", "Mudanza", "Propietario Agotado", "Reparaciones Mayores", "Reducción de Espacio", "Venta de Sucesión", "Dificultad Financiera", "Otro / Prefiero No Decir"],
      reasonDefault: "Selecciona un motivo...",
      cta: "Continuar",
      submitCta: "Enviar y Obtener Mi Oferta",
      microcopy: "Sin obligación · Sin spam · 100% gratis",
      successTitle: "Todo listo,",
      successSub: "Hemos recibido tu solicitud y un miembro de nuestro equipo se comunicará contigo dentro de las 24 horas con tu oferta en efectivo. Sin presión, sin compromiso.",
      successMicro: ["Sin obligación", "Sin presión", "Solo una oferta justa"],
      privacyNote: "Al enviar, aceptas ser contactado por nuestro equipo. Respetamos tu privacidad — sin spam, sin compartir tu información con terceros, nunca.",
      editLabel: "Editar",
      backLabel: "Atrás",
      summaryLabels: { property: "Propiedad", contact: "Contacto", details: "Detalles" },
    },
    finalCta: {
      headline: "La oferta está esperando.",
      headlineItalic: "El próximo paso es tuyo.",
      sub: "Sin obligación. Sin prisa. Solo una oferta justa en efectivo de un equipo que genuinamente respeta tu tiempo, tu situación y tu hogar.",
      cta: "Obtener Mi Oferta Gratis",
      micros: ["Sin obligación", "Sin reparaciones", "Sin comisiones", "Cierra en 7 días"],
    },
    // Mobile-specific
    mobileHero: {
      eyebrow: "Oferta en Efectivo · 24 Horas",
      headline: "Vende Rápido.",
      headlineItalic: "Recibe Efectivo.",
      sub: "Sin reparaciones. Sin agentes. Sin cargos ocultos.",
      addressPlaceholder: "Ingresa la dirección de tu propiedad",
      cta: "Obtener Mi Oferta en Efectivo",
      microcopy: "Sin compromiso · Gratis · 2 minutos",
      stats: [
        { value: "500+", label: "Casas Compradas" },
        { value: "24hr", label: "Tiempo Oferta" },
        { value: "$0", label: "Cargos" },
      ],
    },
    mobilePain: {
      eyebrow: "Entendemos",
      headline: "¿Te suena familiar?",
      sub: "Hemos ayudado a propietarios en cada una de estas situaciones.",
      chips: ["¿Riesgo de ejecución hipotecaria?", "¿Heredaste una casa?", "¿Pasando por un divorcio?", "¿Cansado de inquilinos?", "¿Necesita reparaciones mayores?", "¿Mudándote rápido?", "¿Pagos atrasados?", "¿Reduciendo espacio?", "¿Venta de sucesión?", "¿Propiedad problemática?"],
      empathy: "Cualquiera que sea tu situación — te encontramos donde estás,",
      empathyStrong: "sin juicios ni presión.",
      cta: "Obtener una Oferta Sin Presión",
    },
    mobileForm: {
      eyebrow: "Comenzar",
      headline: "Tu oferta está a",
      headlineItalic: "2 minutos de distancia",
      steps: [
        { title: "¿Dónde está la propiedad?", sub: "Solo la dirección para comenzar.", label: "Dirección de la Propiedad", placeholder: "123 Calle Maple, Atlanta, GA" },
        { title: "¿Cuál es tu número de teléfono?", sub: "Te llamaremos o enviaremos un mensaje con tu oferta.", label: "Número de Teléfono", placeholder: "(555) 000-0000", privacyNote: "Nunca vendemos ni compartimos tu número." },
        { title: "¿Cuál es tu nombre?", sub: "Para saber a quién dirigir tu oferta.", labels: { first: "Nombre", last: "Apellido", email: "Correo (opcional)" }, placeholders: { first: "Nombre", last: "Apellido", email: "tu@ejemplo.com" } },
        { title: "Cuéntanos sobre la propiedad", sub: "Dos preguntas rápidas — no hay respuestas incorrectas." },
        { title: "Todo listo,", sub: "Revisa y envía — tendremos tu oferta en 24 horas." },
      ],
      stepLabels: ["Dirección", "Teléfono", "Nombre", "Detalles", "Confirmar"],
      conditions: [
        { value: "excellent", emoji: "✨", label: "Excelente Estado", sub: "Lista para habitar" },
        { value: "good", emoji: "👍", label: "Buen Estado", sub: "Trabajo cosmético menor" },
        { value: "fair", emoji: "🔨", label: "Necesita Trabajo", sub: "Algunas reparaciones" },
        { value: "poor", emoji: "🏚", label: "Trabajo Mayor", sub: "Daño significativo" },
      ],
      timelines: [
        { value: "asap", label: "Lo Antes Posible", sub: "7–14 días" },
        { value: "30days", label: "30 Días", sub: "Algo urgente" },
        { value: "90days", label: "1–3 Meses", sub: "Planificando" },
        { value: "flexible", label: "Flexible", sub: "Sin fecha límite" },
      ],
      reasons: ["Ejecución Hipotecaria / Pagos Atrasados", "Propiedad Heredada", "Divorcio", "Mudanza", "Propietario Agotado", "Reparaciones Mayores", "Reducción de Espacio", "Venta de Sucesión", "Otro / Prefiero No Decir"],
      reasonDefault: "Selecciona si quieres...",
      conditionLabel: "Condición de la Propiedad",
      timelineLabel: "Tiempo Ideal para Cerrar",
      reasonLabel: "Motivo de Venta",
      reasonOptional: "(opcional)",
      cta: "Continuar",
      submitCta: "Obtener Mi Oferta en Efectivo",
      microcopy: "Sin compromiso · Sin spam · Gratis",
      stepsLeft: (n: number) => `${n} paso${n > 1 ? "s" : ""} más`,
      readyLabel: "Listo para enviar",
      successTitle: "Todo listo,",
      successSub: "Nuestro equipo se comunicará dentro de las 24 horas con tu oferta en efectivo. Sin presión, sin compromiso.",
      callLabel: "¿Prefieres hablar ahora? Llámanos.",
      privacyNote: "Al enviar, aceptas ser contactado sobre tu propiedad. Respetamos tu privacidad — sin spam, sin terceros.",
      editLabel: "Editar",
      backLabel: "← Atrás",
      summaryLabels: { property: "Propiedad", phone: "Teléfono", name: "Nombre", condition: "Condición" },
    },
    // Voice Agent UI (Spanish)
    voice: {
      idleTitle: "Obtén tu oferta en efectivo en 2 minutos.",
      idleSub: "Toca para comenzar una conversación rápida — sin formularios, sin escribir. Te haré unas preguntas y nuestro equipo te llamará con una oferta justa, sin compromiso.",
      startButton: "Toca para Hablar",
      startingLabel: "Conectando…",
      connectingLabel: "Conectando…",
      listeningLabel: "Escuchando",
      speakingLabel: "Hablando",
      thinkingLabel: "Pensando…",
      endCallLabel: "Finalizar",
      muteLabel: "Silenciar",
      unmuteLabel: "Activar micro",
      fallbackLink: "¿Prefieres escribir? Completa un formulario rápido",
      typeHint: "¿Prefieres escribir? También puedes responder aquí.",
      typeQueuedHint: "Escribe tu respuesta aquí. La enviaré en cuanto se conecte la llamada.",
      typePlaceholder: "Escribe tu respuesta aquí",
      typeSend: "Enviar",
      learnMoreLink: "Conoce más sobre nosotros ↓",
      micBlockedTitle: "Micrófono bloqueado",
      micBlockedSub: "Necesito tu micrófono para conversar — es mucho más rápido que escribir. Haz clic en el candado en la barra de direcciones, selecciona Micrófono Permitir, y recarga la página.",
      micBlockedRetry: "Ya lo permití — intentar de nuevo",
      micBlockedFallback: "¿No puedes usar el micro? Completa un formulario",
      errorTitle: "Algo salió mal",
      errorSub: "La llamada no se conectó. Intentémoslo de nuevo, o puedes completar un formulario rápido.",
      errorRetry: "Intentar de nuevo",
      successTitle: "Gracias,",
      successSub: "Tenemos lo que necesitamos. Nuestro equipo te llamará en 24 horas con tu oferta en efectivo — sin compromiso.",
      successMicro: ["Sin obligación", "Sin presión", "Solo una oferta justa"],
      summaryTitle: "Esto es lo que capturamos",
      summaryEmpty: "No proporcionado",
      summaryLabels: {
        address: "Dirección de la propiedad",
        name: "Nombre",
        phone: "Teléfono",
        email: "Correo electrónico",
        condition: "Condición",
        timeline: "Tiempo",
        reason: "Motivo de venta",
      },
      summaryValues: {
        condition: {
          excellent: "Excelente estado",
          good: "Buen estado",
          fair: "Necesita algunas reparaciones",
          needs_work: "Necesita trabajo",
        },
        timeline: {
          asap: "Lo antes posible",
          "1_3_months": "1-3 meses",
          "3_6_months": "3-6 meses",
          exploring: "Solo explorando",
        },
      },
      trustRow: ["SSL Seguro", "Sin Spam", "Datos Protegidos"],
    },

  },
} as const;

export type SiteContent = typeof content.en;
